# Generated by Django 3.2.9 on 2021-12-04 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_service', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=255)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxapi.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('service_description', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type_of_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxapi.typeofservice')),
            ],
        ),
    ]
